# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose-2.4.yml up -d
version: '3.8'
# docker-compose -f docker-compose-app.yml up -d
# 你需要修改system为你自身系统的仓库名
services:

  # 部署前端项目（含 API 反向代理）
  ai-mcp-gateway-admin:
    image: registry.cn-hangzhou.aliyuncs.com/xfg-studio/nginx:latest
    container_name: nginx-admin
    restart: always
    ports:
      - '8443:443'
      - '8000:80'
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html
    privileged: true
    networks:
      - my-network
      - infra-network

  # Nginx 负载均衡器
  ai-mcp-gateway-distributed:
    image: registry.cn-hangzhou.aliyuncs.com/xfg-studio/nginx:latest
    container_name: ai-mcp-gateway-distributed
    restart: always
    ports:
      - '7443:443'
      - '8777:80'
    volumes:
      - ./distributed/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./distributed/nginx/html:/usr/share/nginx/html
    privileged: true
    networks:
      - my-network
      - infra-network

  ai-mcp-gateway-app-01:
    image: registry.cn-hangzhou.aliyuncs.com/fuzhengwei/ai-mcp-gateway-app:1.0.0
    container_name: ai-mcp-gateway-app-01
    restart: on-failure
    ports:
      - "8771:8777"
    environment:
      - TZ=PRC
      - SERVER_PORT=8777
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ai_mcp_gateway_v2?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - REDIS_SDK_CONFIG_HOST=redis
      - REDIS_SDK_CONFIG_PORT=6379
      - SPRING_AI_OPENAI_BASE_URL=https://apis.itedus.cn
      - SPRING_AI_OPENAI_API_KEY=sk-Pkiq7dGOZFORKUjm06234e9c173d40C6A8CdAb3aD5Ba7997
      - SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL=gpt-4o
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network
      - infra-network

  ai-mcp-gateway-app-02:
    image: registry.cn-hangzhou.aliyuncs.com/fuzhengwei/ai-mcp-gateway-app:1.0.0
    container_name: ai-mcp-gateway-app-02
    restart: on-failure
    ports:
      - "8772:8777"
    environment:
      - TZ=PRC
      - SERVER_PORT=8777
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ai_mcp_gateway_v2?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - REDIS_SDK_CONFIG_HOST=redis
      - REDIS_SDK_CONFIG_PORT=6379
      - SPRING_AI_OPENAI_BASE_URL=https://apis.itedus.cn
      - SPRING_AI_OPENAI_API_KEY=sk-Pkiq7dGOZFORKUjm06234e9c173d40C6A8CdAb3aD5Ba7997
      - SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL=gpt-4o
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network
      - infra-network

  ai-mcp-gateway-demo-mcp-server-test:
    image: registry.cn-hangzhou.aliyuncs.com/fuzhengwei/ai-mcp-gateway-demo-mcp-server-test:1.0.0
    container_name: ai-mcp-gateway-demo-mcp-server-test
    restart: on-failure
    ports:
      - "8701:8701"
    environment:
      - TZ=PRC
      - SERVER_PORT=8701
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network
      - infra-network

networks:
  my-network:
    driver: bridge
  infra-network:
    external: true
    name: devops_my-network
